export const ADD_TODOS_LOADING="ADD_TODOS_LOADING"
export const ADD_TODOS_SUCCESS="ADD_TODOS_SUCCESS"
export const ADD_TODOS_FAILURE="ADD_TODOS_FAILURE"

export const GET_TODOS_LOADING="GET_TODOS_LOADING"
export const GET_TODOS_SUCCESS="GET_TODOS_SUCCESS"
export const GET_TODOS_FAILURE="GET_TODOS_FAILURE"

export const DELETE_TODOS_LOADING="DELETE_TODOS_LOADING"
export const DELETE_TODOS_SUCCESS="DELETE_TODOS_SUCCESS"
export const DELETE_TODOS_FAILURE="DELETE_TODOS_FAILURE"


export const UPDATE_TODOS_LOADING="UPDATE_TODOS_LOADING"
export const UPDATE_TODOS_SUCCESS="UPDATE_TODOS_SUCCESS"
export const UPDATE_TODOS_FAILURE="UPDATE_TODOS_FAILURE"